name: Codespell
on: [push, pull_request]
permissions: {}
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@master
        with:
          skip: yarn.lock,./extensions/*/js/dist/*.js,./extensions/*/js/dist/*.js.map,./framework/core/js/dist/*.js.map,./framework/core/js/dist/*.js
